create table if not exists public.classified_conversations (
  id uuid primary key default gen_random_uuid(),
  classified_id uuid not null references public.classifieds(id) on delete cascade,
  buyer_id uuid not null references auth.users(id) on delete cascade,
  seller_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (classified_id, buyer_id),
  check (buyer_id <> seller_id)
);

create table if not exists public.classified_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.classified_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1500),
  created_at timestamptz not null default now()
);

create index if not exists classified_conversations_buyer_updated_idx
  on public.classified_conversations (buyer_id, updated_at desc);

create index if not exists classified_conversations_seller_updated_idx
  on public.classified_conversations (seller_id, updated_at desc);

create index if not exists classified_conversations_classified_idx
  on public.classified_conversations (classified_id);

create index if not exists classified_messages_conversation_created_idx
  on public.classified_messages (conversation_id, created_at asc);

create index if not exists classified_messages_sender_idx
  on public.classified_messages (sender_id);

alter table public.classified_conversations enable row level security;
alter table public.classified_messages enable row level security;

revoke all on table public.classified_conversations from anon, authenticated;
revoke all on table public.classified_messages from anon, authenticated;

grant select, insert on table public.classified_conversations to authenticated;
grant select, insert on table public.classified_messages to authenticated;

create policy "Participants can read classified conversations"
on public.classified_conversations
for select
to authenticated
using (
  (select auth.uid()) = buyer_id
  or (select auth.uid()) = seller_id
);

create policy "Buyers can start published classified conversations"
on public.classified_conversations
for insert
to authenticated
with check (
  (select auth.uid()) = buyer_id
  and buyer_id <> seller_id
  and exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.status = 'published'
      and c.published_at is not null
      and c.published_at <= now()
      and c.owner_id = seller_id
      and c.owner_id <> (select auth.uid())
  )
);

create policy "Participants can read classified messages"
on public.classified_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.classified_conversations cc
    where cc.id = conversation_id
      and (
        cc.buyer_id = (select auth.uid())
        or cc.seller_id = (select auth.uid())
      )
  )
);

create policy "Participants can send classified messages"
on public.classified_messages
for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1
    from public.classified_conversations cc
    where cc.id = conversation_id
      and (
        cc.buyer_id = (select auth.uid())
        or cc.seller_id = (select auth.uid())
      )
  )
);

create or replace function private.touch_classified_conversation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public.classified_conversations
  set updated_at = new.created_at
  where id = new.conversation_id;

  return new;
end;
$$;

revoke all on function private.touch_classified_conversation() from public, anon, authenticated;

drop trigger if exists classified_messages_touch_conversation on public.classified_messages;
create trigger classified_messages_touch_conversation
after insert on public.classified_messages
for each row
execute function private.touch_classified_conversation();
