-- Applied to the isolated acheguese-v2 project.
create schema if not exists private;

create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  ibge_code integer unique,
  state_code text not null check (char_length(state_code) = 2),
  name text not null check (char_length(name) between 2 and 120),
  slug text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (state_code, slug)
);

create table if not exists public.classified_categories (
  id text primary key,
  label text not null check (char_length(label) between 2 and 80),
  sort_order smallint not null default 0,
  is_active boolean not null default true
);

insert into public.classified_categories (id, label, sort_order)
values
  ('vehicles', 'Veículos', 10),
  ('real-estate', 'Imóveis', 20),
  ('electronics', 'Eletrônicos', 30),
  ('home', 'Casa e móveis', 40),
  ('fashion', 'Moda', 50),
  ('sports', 'Esportes', 60),
  ('pets', 'Animais', 70),
  ('other', 'Outros', 80)
on conflict (id) do update
set
  label = excluded.label,
  sort_order = excluded.sort_order;

create table if not exists public.classifieds (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  category_id text not null references public.classified_categories(id),
  city_id bigint not null references public.cities(id),
  slug text not null unique,
  title text not null check (char_length(title) between 5 and 120),
  description text not null check (char_length(description) between 20 and 5000),
  condition text not null check (condition in ('new', 'like_new', 'used', 'for_parts')),
  price_cents bigint check (price_cents is null or price_cents >= 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  neighborhood text check (neighborhood is null or char_length(neighborhood) <= 120),
  status text not null default 'draft'
    check (status in ('draft', 'pending_review', 'published', 'paused', 'sold', 'rejected', 'archived')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_vector tsvector generated always as (
    to_tsvector(
      'portuguese',
      coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(neighborhood, '')
    )
  ) stored,
  check (
    (status = 'published' and published_at is not null)
    or status <> 'published'
  )
);

create table if not exists private.classified_locations (
  classified_id uuid primary key references public.classifieds(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_meters integer check (accuracy_meters is null or accuracy_meters >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.classified_media (
  id uuid primary key default gen_random_uuid(),
  classified_id uuid not null references public.classifieds(id) on delete cascade,
  storage_key text not null unique,
  alt text not null default '' check (char_length(alt) <= 200),
  position smallint not null check (position between 0 and 9),
  created_at timestamptz not null default now(),
  unique (classified_id, position)
);

create table if not exists public.classified_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  classified_id uuid not null references public.classifieds(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, classified_id)
);

create table if not exists public.classified_reports (
  id uuid primary key default gen_random_uuid(),
  classified_id uuid not null references public.classifieds(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null
    check (reason in ('fraud', 'prohibited', 'duplicate', 'wrong_category', 'harassment', 'other')),
  details text check (details is null or char_length(details) <= 2000),
  created_at timestamptz not null default now(),
  unique (classified_id, reporter_id)
);

create table if not exists private.classified_moderation (
  classified_id uuid primary key references public.classifieds(id) on delete cascade,
  reviewer_id uuid references auth.users(id) on delete set null,
  decision text check (decision in ('approved', 'rejected', 'needs_changes')),
  internal_notes text,
  reviewed_at timestamptz
);

create index if not exists classifieds_owner_updated_idx
  on public.classifieds (owner_id, updated_at desc);

create index if not exists classifieds_public_feed_idx
  on public.classifieds (city_id, published_at desc)
  where status = 'published';

create index if not exists classifieds_category_feed_idx
  on public.classifieds (category_id, city_id, published_at desc)
  where status = 'published';

create index if not exists classifieds_search_idx
  on public.classifieds using gin (search_vector);

create index if not exists classified_media_parent_idx
  on public.classified_media (classified_id, position);

create index if not exists classified_reports_parent_idx
  on public.classified_reports (classified_id, created_at desc);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public;

drop trigger if exists classifieds_set_updated_at on public.classifieds;
create trigger classifieds_set_updated_at
before update on public.classifieds
for each row
execute function private.set_updated_at();

alter table public.cities enable row level security;
alter table public.classified_categories enable row level security;
alter table public.classifieds enable row level security;
alter table public.classified_media enable row level security;
alter table public.classified_favorites enable row level security;
alter table public.classified_reports enable row level security;
alter table private.classified_locations enable row level security;
alter table private.classified_moderation enable row level security;

revoke all on table public.cities from anon, authenticated;
revoke all on table public.classified_categories from anon, authenticated;
revoke all on table public.classifieds from anon, authenticated;
revoke all on table public.classified_media from anon, authenticated;
revoke all on table public.classified_favorites from anon, authenticated;
revoke all on table public.classified_reports from anon, authenticated;

grant select on table public.cities to anon, authenticated;
grant select on table public.classified_categories to anon, authenticated;
grant select on table public.classifieds to anon, authenticated;
grant insert, update, delete on table public.classifieds to authenticated;
grant select on table public.classified_media to anon, authenticated;
grant insert, update, delete on table public.classified_media to authenticated;
grant select, insert, delete on table public.classified_favorites to authenticated;
grant select, insert on table public.classified_reports to authenticated;

create policy "Active cities are public"
on public.cities
for select
to anon, authenticated
using (is_active = true);

create policy "Active classified categories are public"
on public.classified_categories
for select
to anon, authenticated
using (is_active = true);

create policy "Published classifieds are public"
on public.classifieds
for select
to anon, authenticated
using (
  status = 'published'
  and published_at is not null
  and published_at <= now()
);

create policy "Owners can read their classifieds"
on public.classifieds
for select
to authenticated
using (
  (select auth.uid()) is not null
  and (select auth.uid()) = owner_id
);

create policy "Owners can create draft classifieds"
on public.classifieds
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and (select auth.uid()) = owner_id
  and status = 'draft'
  and published_at is null
);

create policy "Owners can update their classifieds"
on public.classifieds
for update
to authenticated
using (
  (select auth.uid()) is not null
  and (select auth.uid()) = owner_id
)
with check (
  (select auth.uid()) = owner_id
  and status in ('draft', 'pending_review', 'paused', 'sold', 'archived')
  and (
    status <> 'draft'
    or published_at is null
  )
);

create policy "Owners can delete their classifieds"
on public.classifieds
for delete
to authenticated
using (
  (select auth.uid()) is not null
  and (select auth.uid()) = owner_id
);

create policy "Published classified media is public"
on public.classified_media
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.status = 'published'
      and c.published_at is not null
      and c.published_at <= now()
  )
);

create policy "Owners can read classified media"
on public.classified_media
for select
to authenticated
using (
  exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.owner_id = (select auth.uid())
  )
);

create policy "Owners can add classified media"
on public.classified_media
for insert
to authenticated
with check (
  exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.owner_id = (select auth.uid())
      and c.status in ('draft', 'pending_review', 'paused')
  )
);

create policy "Owners can update classified media"
on public.classified_media
for update
to authenticated
using (
  exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.owner_id = (select auth.uid())
  )
);

create policy "Owners can delete classified media"
on public.classified_media
for delete
to authenticated
using (
  exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.owner_id = (select auth.uid())
  )
);

create policy "Users can read their favorites"
on public.classified_favorites
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can add their favorites"
on public.classified_favorites
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.status = 'published'
  )
);

create policy "Users can delete their favorites"
on public.classified_favorites
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their reports"
on public.classified_reports
for select
to authenticated
using ((select auth.uid()) = reporter_id);

create policy "Users can report published classifieds"
on public.classified_reports
for insert
to authenticated
with check (
  (select auth.uid()) = reporter_id
  and exists (
    select 1
    from public.classifieds c
    where c.id = classified_id
      and c.status = 'published'
  )
);
